AllCops:
  Exclude:
    - "opencensus-jaeger.gemspec"
    - "test/**/*"
    - "thrift/**/*"
    - "examples/**/*"

Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/ModuleFunction:
  Enabled: false

Metrics/LineLength:
  Max: 120
