AllCops:
  Exclude:
    - "opencensus.gemspec"
    - "test/**/*"

Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false

Metrics/LineLength:
  Max: 120
