version: 2

test: &test
    - checkout
    - run: bundle install --path vendor/bundle --jobs=4 --retry=3
    - run: bundle exec rspec

jobs:
  test-2.4:
    steps: *test
    docker:
      - image: circleci/ruby:2.4-stretch
        environment:
          LOG_LEVEL: DEBUG

  test-2.5:
    steps: *test
    docker:
      - image: circleci/ruby:2.5-stretch
        environment:
          LOG_LEVEL: DEBUG

  test-2.6:
    steps: *test
    docker:
      - image: circleci/ruby:2.6-stretch
        environment:
          LOG_LEVEL: DEBUG

  test-2.7:
    steps: *test
    docker:
      - image: circleci/ruby:2.7-stretch
        environment:
          LOG_LEVEL: DEBUG

workflows:
  version: 2
  test:
    jobs:
      - test-2.4:
          context: org-global
      - test-2.5:
          context: org-global
      - test-2.6:
          context: org-global
      - test-2.7:
          context: org-global
